name: colorize
channels:
- fastai
- conda-forge
- defaults
dependencies:
- pip
- fastai=1.0.60
- python=3.10
- tensorboardX
- jupyterlab
- pillow>=9.0.0
- ipywidgets
- ffmpeg
- python-dotenv
- pip:
  - ffmpeg-python
  - opencv-python>=4.2.0.32
  - wandb
  - yt-dlp
  - torch==1.11.0
  - torchvision==0.12.0
  - fastapi
  - uvicorn
  - python-multipart